config/routes.rb
# frozen_string_literal: true

Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :collaborators, only: [:index, :destroy, :edit, :update]
  end
  resources :collaborators, only: [:new, :edit, :create, :show, :update]
end

app/models/spree/collaborator.rb
class Spree::Collaborator < ApplicationRecord
  attr_accessor :authenticity_token, :commit, :collaborator
end

app/models/spree/collaborators_ability.rb
# frozen_string_literal: true

class Spree::CollaboratorsAbility
  include CanCan::Ability

  def initialize(user)
    collaborator_ability_class = self.class

    user ||= Spree::Collaborator.new # guest user (not logged in)

    if user
      can :create, :edit, :update, Spree::Collaborators
    else
      can :manage, :all
    end
  end
end

app/models/spree/collaborators_configuration.rb
# frozen_string_literal: true

class Spree::CollaboratorsConfiguration < Spree::Preferences::Configuration
  def self.boolean_preferences
    %w(show_email)
  end

  preference :show_email, :boolean, default: false
end

app/models/spree/permission_sets/collaborator_display.rb
# frozen_string_literal: true

module Spree
  module PermissionSets
    class CollaboratorDisplay < PermissionSets::Base
      def activate!
        can [:display, :admin], Spree::Collaborator
      end
    end
  end
end

app/models/spree/permission_sets/collaborator_management.rb
# frozen_string_literal: true

module Spree
  module PermissionSets
    class CollaboratorManagement < PermissionSets::Base
      def activate!
        can :manage, Spree::Collaborator
      end
    end
  end
end

app/controllers/spree/admin/collaborators_controller.rb
# frozen_string_literal: true

module Spree
  module Admin
    class CollaboratorsController < Spree::Admin::ResourceController
      def index
        @collaborators = collection
      end

      def edit
        @collaborator = Spree::Collaborator.find(params[:id])
        authorize! :update, @collaborator
      end

      def update
        @collaborator = Spree::Collaborator.find(params[:id])

        authorize! :update, @collaborator
        if @collaborator.update(collabs_params)
          flash[:notice] = I18n.t('spree.purchase_policy_successfully_submitted')
          redirect_to spree.collaborator_path(@collaborator)
        else
          render :edit
        end
      end

      private

      def permitted_collabs_attributes
        %i[name address phone_number email sex]
      end

      def collabs_params
        params.require(:collaborator).permit(permitted_collabs_attributes)
      end

      def collection
        params[:q] ||= {}

        @search = Spree::Collaborator.ransack(params[:q])
        @collection = @search.result.page(params[:page]).per(params[:per_page])
      end
    end
  end
end

app/controllers/spree/collaborators_controller.rb
# frozen_string_literal: true

module Spree
  class CollaboratorsController < Spree::StoreController
    helper Spree::BaseHelper
    def show
      @collaborator = Spree::Collaborator.find(params[:id])
    end

    def new
      @collaborator = Spree::Collaborator.new
    end

    def edit
      @collaborator = Spree::Collaborator.find(params[:id])
    end

    def create
      @collaborator = Spree::Collaborator.new(collabs_params)
      if @collaborator.save
        flash[:notice] = I18n.t('spree.purchase_policy_successfully_submitted')
        redirect_to spree.collaborator_path(@collaborator)
      else
        render :new
      end
    end

    def update
      @collaborator = Spree::Collaborator.find(params[:id])

      if @collaborator.update(collabs_params)
        flash[:notice] = I18n.t('spree.purchase_policy_successfully_submitted')
        redirect_to spree.collaborator_path(@collaborator)
      else
        render :edit
      end
    end

    private

    def permitted_collabs_attributes
      [:name, :address, :phone_number, :email, :sex]
    end

    def collabs_params
      params.require(:collaborator).permit(permitted_collabs_attributes)
    end
  end
end

app/views/spree/admin/collaborators/_form.html.erb
<%= render "spree/shared/error_messages", target: @collaborator %>
<%= f.field_container :name do %>
  <%= f.label :name %><br />
  <%= f.text_field :name, maxlength: "255", size: "60" %>
<% end %>

<%= f.field_container :address do %>
  <%= f.label :address %><br />
  <%= f.text_field :address, maxlength: "255", size: "60" %>
<% end %>

<%= f.field_container :phone_number do %>
  <%= f.label :phone_number %><br />
  <%= f.text_field :phone_number, maxlength: "255", size: "60" %>
<% end %>

<%= f.field_container :email do %>
  <%= f.label :email %><br />
  <%= mail_to @collaborator.email %>
<% end %>

<%= f.field_container :sex do %>
  <%= f.label :sex %><br />
  <%= f.select :sex, [
    ['Nam', true],
    ['Nữ', false]
    ], {}, class: 'select2 fullwidth'  -%>
<% end %>

app/views/spree/admin/collaborators/edit.html.erb
<% content_for :page_title do %>
	<%= I18n.t("spree.editing_collaborator_for_html") %>
<% end %>

<%= form_for([:admin, @collaborator]) do |f| %>
	<div class="alpha eight columns">
		<% unless @collaborator.name.blank? %>
			<h2><%= @collaborator.name %></h2>
		<% end %>
		<p>
			<%= simple_format(@collaborator.email) %>
		</p>
	</div>

	<div class="omega eight columns">
		<%= render 'form', f: f %>
	</div>

	<div class="clear"></div>

	<fieldset class="no-border-top">
		<% if can? :manage, Spree::Collaborator %>
			<%= render 'spree/admin/shared/edit_resource_links' %>
		<% end %>
	</fieldset>
<% end %>

app/views/spree/admin/collaborators/index.html.erb
<% content_for :page_title do %>
  <%= I18n.t("spree.collaborators") %>
<% end %>

<% content_for :table_filter_title do %>
  <% if can? :display, Spree::Collaborator %>
    <%= I18n.t("spree.search") %>
  <% end %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_reviews_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="alpha three columns">
        <div class="field">
          <%= f.label :name_cont, I18n.t("spree.name") %><br />
          <%= f.text_field :name_cont, class: 'fullwidth' %>
        </div>
      </div>

      <div class="seven columns">
        <div class="field">
          <%= f.label :address_cont, I18n.t("spree.address") -%><br/>
          <%= f.text_field :address_cont, class: 'fullwidth'  -%>
        </div>
      </div>

      <div class="seven columns">
        <div class="field">
          <%= f.label :phone_number_cont, I18n.t("spree.phone_number") -%><br/>
          <%= f.text_field :phone_number_cont, class: 'fullwidth'  -%>
        </div>
      </div>

      <div class="seven columns">
        <div class="field">
          <%= f.label :email_cont,I18n.t("spree.email") -%><br/>
          <%= f.text_field :email_cont, class: 'fullwidth'  -%>
        </div>
      </div>

      <div class="two columns omega">
        <div class="field">
          <%= f.label :sex_eq, I18n.t("spree.sex") -%><br/>
          <%= f.select :sex_eq, [
            ['Nam', true],
            ['Nữ', false]
            ], {}, class: 'select2 fullwidth'  -%>
        </div>
      </div>

      <div class="clear"></div>

      <div class="form-buttons actions filter-actions" data-hook="admin_reviews_index_search_buttons">
        <%= button_tag I18n.t("spree.search") %>
      </div>
    <%- end -%>
  </div>
<%- end -%>

<%= paginate @collaborators, theme: "solidus_admin" %>

<% if @collaborators.any? %>
  <table class="index">
    <colgroup>
      <col style="width: 20%;">
      <col style="width: 10%;">
      <col style="width: 10%;">
      <col style="width: 15%;">
      <col style="width: 15%;">
      <col style="width: 15%;">
    </colgroup>
    <thead>
      <tr>
        <th><%= Spree::Collaborator.human_attribute_name(:name) %></th>
        <th><%= Spree::Collaborator.human_attribute_name(:address) %></th>
        <th><%= Spree::Collaborator.human_attribute_name(:phone_number) %></th>
        <th><%= Spree::Collaborator.human_attribute_name(:email) %></th>
        <th><%= Spree::Collaborator.human_attribute_name(:sex) %></th>
        <th><%= Spree::Collaborator.human_attribute_name(:created_at) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <%- @collaborators.each do |collaborator| -%>
        <tr id="<%= dom_id collaborator %>">
          <td class="align-center">
            <%= collaborator.name %>
          </td>
          <td class="align-center">
            <%= collaborator.address%>
          </td>
          <td class="align-center">
            <%= collaborator.phone_number %>
          </td>
          <td class="align-center">
            <%= collaborator.email %>
          </td>
          <td class="align-center">
            <%= collaborator.sex %>
          </td>
          <td class="align-center">
            <%= l collaborator.created_at, format: :short %>
          </td>
          <td class="actions">
            <% if can? :manage, Spree::Collaborator %>
              <%= link_to_edit collaborator, no_text: true, class: 'edit' %>
              <%= link_to_delete collaborator, no_text: true %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= I18n.t("spree.no_results") %>
  </div>
<% end %>

<%= paginate @collaborators, theme: "solidus_admin" -%>

app/views/spree/collaborators/_form.html.erb
<%= form_for collaborator, url: collaborators_path, html: { method: :post, multipart: true} do |f| %>
  <%= render "spree/shared/error_messages", target: collaborator %>


  <p class="review_name_field">
    <%= f.label :name %><br />
    <%= f.text_field :name, maxlength: "255", size: "50" %>
  </p>

  <p class="review_name_field">
    <%= f.label :address %><br />
    <%= f.text_field :address, maxlength: "255", size: "50" %>
  </p>

  <p class="review_title_field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number, maxlength: "255", size: "50" %>
  </p>

  <p class="form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, maxlength: "255", size: "50" %>
  </p>

  <p class="review_name_field">
    <%= f.label :sex %><br />
    <%= f.select :sex, [
      ['Nam', true],
      ['Nữ', false]
      ], {}, class: 'select2 fullwidth'  -%>
  </p>

  <p class="review_submit">
    <%= f.submit I18n.t("spree.submit_your_collaborator"), class: "button bg_darkfirst" %>
  </p>
<% end %>

app/views/spree/collaborators/edit.html.erb
<%= content_tag :h2, I18n.t("spree.leave_us"), class: 'new-review-title' %>

<%= render 'form', collaborator: @collaborator %>

app/views/spree/collaborators/new.html.erb
<%= content_tag :h2, I18n.t("spree.become_a_collaborator"), class: 'new-review-title' %>

<%= render 'form', collaborator: @collaborator %>

app/views/spree/collaborators/show.html.erb
<%= render partial: "spree/shared/collaborator", locals: {collaborator: @collaborator} %>

app/views/spree/shared/_collaborator.html.erb
<div class="review" itemprop="reviews" itemscope="itemscope" itemtype="http://schema.org/Review">
  <span itemprop="name"><%= collaborator.name %></span>
  <span itemprop="name"><%= collaborator.email %></span>
  <br/>
  <span class="attribution"><%= I18n.t("spree.submitted_on") %>
    <strong><%= l collaborator.created_at.to_date %></strong>
  </span>
  <meta itemprop="datePublished" content="<%= collaborator.created_at.to_date.to_s %>"/>

  <div itemprop="reviewBody">
    <h1>Register Collaborator SuccessFully</h1>
  </div>
</div>